title: Scarapalooza
description: scarameow
theme: just-the-docs

url: https://umbreon19.github.io/scarapalooza/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
